default_language_version:
  python: python3.9
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: check-yaml
    - id: check-added-large-files
    - id: name-tests-test
- repo: https://github.com/pre-commit-ci/pre-commit-ci-config
  rev: v1.4.0
  hooks:
    - id: check-pre-commit-ci-config
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black", "--filter-files"]
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
    - id: black
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.0
  hooks:
    - id: pyupgrade
      args: [--py36-plus]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.931
  hooks:
    - id: mypy
      exclude: ^(docs/|example-plugin/)
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      args: ["./src"]
      language: python
      types: [python]
    - id: pytest
      name: pytest
      entry: pytest
      args: ["./src", "--tb=no", "--disable-pytest-warnings"]
      language: python
      types: [python]
